name: contextual
description: >
  A structured logging library for Dart with support for multiple output channels,
  customizable formatting, context management, and middleware processing.

version: 1.2.0
repository: https://github.com/kingwill101/contextual
topics:
  - logging
  - structured-logging
  - middleware
  - observability
  - telemetry

homepage: https://github.com/kingwill101/contextual

issue_tracker: https://github.com/kingwill101/contextual/issues
funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  universal_io: ^2.2.2
  ansicolor: ^2.0.3
  intl: ^0.20.2
  gato: ^0.0.5+1
  dart_mappable: ^4.3.0

dev_dependencies:
  lints: ^6.0.0
  mockito: ^5.5.1
  test: ^1.26.3
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.3.0
