name:  contextual
description: >
  A structured logging library for Dart with support for multiple output channels, 
  customizable formatting, context management, and middleware processing.

version: 1.1.0
repository: https://github.com/kingwill101/contextual
topics: 
  - logging
  - log

homepage: https://github.com/kingwill101/contextual

issue_tracker: https://github.com/kingwill101/contextual/issues
funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace

environment: 
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  universal_io: ^2.2.2
  ansicolor: ^2.0.3
  intl: ^0.20.1
  gato: ^0.0.5+1

dev_dependencies:
  lints: ^5.1.1
  mockito: ^5.4.5
  test: ^1.25.14
