name: contextual_shelf
description: shelf using contextual logger
version: "0.1.0"
resolution: workspace

homepage: https://github.com/kingwill101/contextual/contextual_shelf

issue_tracker: https://github.com/kingwill101/contextual/issues

environment: 
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  contextual: ^1.2.0
  shelf: ^1.4.2